/* ================================================================
   CEYSAN ALUMINYUM — Product Data & Translations
   ================================================================ */

window.CEYSAN = window.CEYSAN || {};

/* ── Products ──────────────────────────────────────────────────── */
CEYSAN.products = [
  {
    id: 1,
    slug: 'isicam-sistemleri',
    category: 'cam',
    tr_name: 'Isıcam Sistemleri',
    en_name: 'Insulated Glass Systems',
    tr_desc: 'Enerji tasarrufu sağlayan çift ve üçlü cam sistemleri. Ses ve ısı yalıtımında üstün performans.',
    en_desc: 'Energy-saving double and triple glazing systems offering superior thermal and acoustic insulation.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_161925165814680.png',
    tr_tags: ['ısı yalıtımı', 'ses yalıtımı', 'enerji tasarrufu'],
    en_tags: ['thermal insulation', 'sound insulation', 'energy saving'],
  },
  {
    id: 2,
    slug: 'pimapen-pencere-sistemleri',
    category: 'pvc',
    tr_name: 'Pimapen Pencere Sistemleri',
    en_name: 'PVC Window Systems',
    tr_desc: 'Yüksek kaliteli PVC profilleri ile üretilmiş dayanıklı ve estetik pencere sistemleri.',
    en_desc: 'Durable and aesthetic window systems manufactured from high-quality PVC profiles.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730796158940348448.jpg',
    tr_tags: ['pvc pencere', 'pimapen', 'çift cam'],
    en_tags: ['pvc window', 'double glazed', 'thermal'],
  },
  {
    id: 3,
    slug: 'panjur-sistemleri',
    category: 'kepenk',
    tr_name: 'Panjur Sistemleri',
    en_name: 'Roller Shutter Systems',
    tr_desc: 'Güneş kontrolü ve gizlilik için manuel ve motorlu panjur çözümleri.',
    en_desc: 'Manual and motorised roller shutter solutions for sun control and privacy.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307954501627680637.jpeg',
    tr_tags: ['panjur', 'güneş kontrolü', 'motorlu'],
    en_tags: ['roller shutter', 'sun control', 'motorised'],
  },
  {
    id: 4,
    slug: 'otomatik-kepenk-sistemleri',
    category: 'kepenk',
    tr_name: 'Otomatik Kepenk Sistemleri',
    en_name: 'Automatic Roller Shutter Systems',
    tr_desc: 'İşyerleri ve depolar için güvenlik öncelikli motorlu kepenk sistemleri.',
    en_desc: 'Security-first motorised roller shutter systems for commercial and industrial use.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307955081277983857.jpeg',
    tr_tags: ['otomatik kepenk', 'motorlu kepenk', 'güvenlik'],
    en_tags: ['automatic shutter', 'motorised', 'security'],
  },
  {
    id: 5,
    slug: 'cam-balkon-sistemleri',
    category: 'cam',
    tr_name: 'Cam Balkon Sistemleri',
    en_name: 'Glass Balcony Systems',
    tr_desc: 'Balkonlarınızı dört mevsim kullanılabilir yaşam alanına dönüştüren modern cam balkon sistemleri.',
    en_desc: 'Modern glass balcony systems that transform your balcony into a year-round living space.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730795591592836906.jpeg',
    tr_tags: ['cam balkon', 'kış bahçesi', 'balkon kapatma'],
    en_tags: ['glass balcony', 'winter garden', 'balcony enclosure'],
  },
  {
    id: 6,
    slug: 'aluminyum-dograma-sistemleri',
    category: 'aluminyum',
    tr_name: 'Alüminyum Doğrama Sistemleri',
    en_name: 'Aluminium Joinery Systems',
    tr_desc: 'Yüksek mukavemetli alüminyum profiller ile özel ölçülerde üretilen kapı ve pencere sistemleri.',
    en_desc: 'Custom-sized door and window systems manufactured from high-strength aluminium profiles.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307956391740415725.jpeg',
    tr_tags: ['alüminyum doğrama', 'alüminyum kapı', 'alüminyum pencere'],
    en_tags: ['aluminium joinery', 'aluminium door', 'aluminium window'],
  },
  {
    id: 7,
    slug: 'otomatik-pergole-sistemleri',
    category: 'dis-mekan',
    tr_name: 'Otomatik Pergole Sistemleri',
    en_name: 'Automatic Pergola Systems',
    tr_desc: 'Yağmur sensörlü ve motorlu tavan sistemleri ile dış mekanlarınızı her koşulda koruyun.',
    en_desc: 'Rain-sensor motorised roof systems to protect your outdoor spaces in all conditions.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730795703876593671.jfif',
    tr_tags: ['pergole', 'otomatik tavan', 'motorlu çatı'],
    en_tags: ['pergola', 'automatic roof', 'motorised canopy'],
  },
  {
    id: 8,
    slug: 'aluminyum-kupeste',
    category: 'aluminyum',
    tr_name: 'Alüminyum Küpeşte',
    en_name: 'Aluminium Handrail Systems',
    tr_desc: 'Merdiven ve balkonlar için şık ve dayanıklı alüminyum korkuluk ve küpeşte sistemleri.',
    en_desc: 'Elegant and robust aluminium railing and handrail systems for stairs and balconies.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307957991748509017.jpeg',
    tr_tags: ['küpeşte', 'korkuluk', 'merdiven korkuluğu'],
    en_tags: ['handrail', 'balustrade', 'railing'],
  },
  {
    id: 9,
    slug: 'giyotin-cam-balkon-sistemleri',
    category: 'cam',
    tr_name: 'Giyotin Cam Balkon Sistemleri',
    en_name: 'Guillotine Glass Balcony Systems',
    tr_desc: 'Çerçevesiz ve görünmez profilli modern giyotin cam balkon sistemleri.',
    en_desc: 'Frameless modern guillotine glass balcony systems with invisible profiles.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730795825129986665.jfif',
    tr_tags: ['giyotin cam', 'çerçevesiz cam', 'sürme cam balkon'],
    en_tags: ['guillotine glass', 'frameless glass', 'sliding glass balcony'],
  },
  {
    id: 10,
    slug: 'dusakabin-sistemleri',
    category: 'ic-mekan',
    tr_name: 'Duşakabin Sistemleri',
    en_name: 'Shower Cabin Systems',
    tr_desc: 'Çeşitli konfigürasyonlarda özel ölçülere göre üretilen şık duşakabin sistemleri.',
    en_desc: 'Custom-sized elegant shower cabin systems in various configurations.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307960201811398340.jpg',
    tr_tags: ['duşakabin', 'cam duş', 'banyo'],
    en_tags: ['shower cabin', 'glass shower', 'bathroom'],
  },
  {
    id: 11,
    slug: 'sineklik-sistemleri',
    category: 'ic-mekan',
    tr_name: 'Sineklik Sistemleri',
    en_name: 'Insect Screen Systems',
    tr_desc: 'Sabit, sürme ve plise sineklik çeşitleri ile böceklerden korunurken temiz hava alın.',
    en_desc: 'Fixed, sliding and pleated insect screen types to keep bugs out while letting fresh air in.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307960711012101376.jpeg',
    tr_tags: ['sineklik', 'plise sineklik', 'sürme sineklik'],
    en_tags: ['insect screen', 'fly screen', 'pleated screen'],
  },
  {
    id: 12,
    slug: 'fotoselli-kapi-sistemleri',
    category: 'endüstriyel',
    tr_name: 'Fotoselli Kapı Sistemleri',
    en_name: 'Automatic Sliding Door Systems',
    tr_desc: 'AVM, hastane ve ofis girişleri için sensörlü otomatik kapı çözümleri.',
    en_desc: 'Sensor-operated automatic door solutions for shopping centres, hospitals and offices.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/resim_yok.png',
    tr_tags: ['fotoselli kapı', 'otomatik kapı', 'sensörlü kapı'],
    en_tags: ['automatic door', 'sensor door', 'sliding entrance'],
  },
  {
    id: 13,
    slug: 'otopark-bariyer-sistemleri',
    category: 'endüstriyel',
    tr_name: 'Otopark Bariyer Sistemleri',
    en_name: 'Parking Barrier Systems',
    tr_desc: 'Yerleşim ve ticari alanlarda güvenli araç giriş-çıkışı için bariyer sistemleri.',
    en_desc: 'Barrier systems for secure vehicle access control in residential and commercial areas.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730796203372950614.jpeg',
    tr_tags: ['bariyer', 'otopark bariyeri', 'geçiş kontrol'],
    en_tags: ['parking barrier', 'access control', 'vehicle barrier'],
  },
  {
    id: 14,
    slug: 'endustriyel-kapi-sistemleri',
    category: 'endüstriyel',
    tr_name: 'Endüstriyel Kapı Sistemleri',
    en_name: 'Industrial Door Systems',
    tr_desc: 'Fabrika, depo ve garaj kapıları için seksiyonel ve çelik endüstriyel kapı çözümleri.',
    en_desc: 'Sectional and steel industrial door solutions for factories, warehouses and garages.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730796295682131794.jpeg',
    tr_tags: ['seksiyonel kapı', 'endüstriyel kapı', 'garaj kapısı'],
    en_tags: ['sectional door', 'industrial door', 'garage door'],
  },
  {
    id: 15,
    slug: 'zip-perde-sistemleri',
    category: 'dis-mekan',
    tr_name: 'Zip Perde Sistemleri',
    en_name: 'Zip Screen Systems',
    tr_desc: 'Rüzgar ve güneş dirençli, motorlu zip perde sistemleri ile dış mekanlarınızı koruyun.',
    en_desc: 'Wind and sun-resistant motorised zip screen systems to protect your outdoor spaces.',
    image: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307963211263789979.jpeg',
    tr_tags: ['zip perde', 'motorlu perde', 'dış cephe perdesi'],
    en_tags: ['zip screen', 'motorised blind', 'external screen'],
  },
];

/* ── Categories ────────────────────────────────────────────────── */
CEYSAN.categories = [
  { id: 'all',       tr: 'Tümü',          en: 'All'           },
  { id: 'cam',       tr: 'Cam Sistemleri', en: 'Glass Systems' },
  { id: 'aluminyum', tr: 'Alüminyum',      en: 'Aluminium'     },
  { id: 'pvc',       tr: 'PVC',            en: 'PVC'           },
  { id: 'kepenk',    tr: 'Kepenk/Panjur',  en: 'Shutters'      },
  { id: 'dis-mekan', tr: 'Dış Mekan',      en: 'Outdoor'       },
  { id: 'ic-mekan',  tr: 'İç Mekan',       en: 'Indoor'        },
  { id: 'endüstriyel', tr: 'Endüstriyel',  en: 'Industrial'    },
];

/* ── UI Translations ───────────────────────────────────────────── */
CEYSAN.i18n = {
  tr: {
    // Nav
    nav_home:        'Ana Sayfa',
    nav_products:    'Ürünler',
    nav_corporate:   'Kurumsal',
    nav_gallery:     'Galeri',
    nav_quote:       'Teklif Al',
    nav_contact:     'İletişim',
    // Hero
    hero_label:      '20+ Yıllık Deneyim',
    hero_title:      'Alüminyum ve PVC Doğrama Sistemleri',
    hero_title_hl:   'Profesyonel Çözümler',
    hero_sub:        'Ümraniye merkezli firmamız; cam balkon, pimapen, alüminyum doğrama ve daha fazlasında İstanbul genelinde hizmet vermektedir.',
    hero_cta1:       'Teklif Al',
    hero_cta2:       'Ürünlerimiz',
    hero_stat1_num:  '20',
    hero_stat1_lbl:  'Yıllık Deneyim',
    hero_stat2_num:  '5000',
    hero_stat2_lbl:  'Tamamlanan Proje',
    hero_stat3_num:  '15',
    hero_stat3_lbl:  'Ürün Kategorisi',
    // Products section
    prod_label:      'Ürün Kategorileri',
    prod_title:      'Tüm Sistemleri Keşfedin',
    prod_sub:        '15 farklı ürün kategorisiyle eviniz, iş yeriniz ve dış mekanlarınız için kapsamlı çözümler sunuyoruz.',
    prod_detail:     'İncele',
    prod_all:        'Tüm Ürünleri Gör',
    // Stats
    stat_exp:        'Yıllık Deneyim',
    stat_proj:       'Tamamlanan Proje',
    stat_cat:        'Ürün Kategorisi',
    stat_dist:       'İlçeye Hizmet',
    stat_sat:        'Müşteri Memnuniyeti',
    // Features
    feat_label:      'Neden CEYSAN?',
    feat_title:      'Kalite ve Güvenin Adresi',
    feat_sub:        '20 yılı aşkın deneyimimizle her projede en yüksek kaliteyi ve müşteri memnuniyetini hedefliyoruz.',
    feat1_title:     'Uzman Ekip',
    feat1_desc:      '20 yıl deneyimli teknik ekibimiz projenizin her aşamasında yanınızda.',
    feat2_title:     'Yerinde Ölçüm & Montaj',
    feat2_desc:      'Ücretsiz keşif ve profesyonel montaj hizmetiyle anahtar teslim çözümler.',
    feat3_title:     'Garantili Ürünler',
    feat3_desc:      'Tüm sistemlerimiz garanti kapsamında olup satış sonrası servis desteği sunulmaktadır.',
    feat4_title:     'İstanbul Genelinde Hizmet',
    feat4_desc:      'İstanbul\'un tüm ilçelerine hızlı ve güvenilir montaj hizmeti.',
    // CTA
    cta_title:       'Ücretsiz Keşif ve Fiyat Teklifi Alın',
    cta_sub:         'Uzman ekibimiz yerinde ölçüm yaparak size en uygun çözümü sunar.',
    cta_btn1:        'Teklif Formu',
    cta_btn2:        'WhatsApp\'tan Yaz',
    // Gallery
    gal_label:       'Projelerimiz',
    gal_title:       'Tamamlanan İşlerimizden',
    gal_sub:         'İstanbul genelinde teslim ettiğimiz gerçek projelerden seçmeler.',
    gal_all:         'Tüm Galeriyi Gör',
    // Search
    search_ph:       'Ürün ara... (örn. cam balkon)',
    search_no:       'Sonuç bulunamadı',
    search_hint1:    'ESC ile kapat',
    search_hint2:    'Enter ile ilk sonuca git',
    // Footer
    footer_desc:     'Ümraniye merkezli firmamız; alüminyum, PVC doğrama ve cam sistemleri alanında 20 yılı aşkın deneyimiyle İstanbul\'a hizmet vermektedir.',
    footer_menu:     'Menü',
    footer_products: 'Ürünler',
    footer_contact:  'İletişim Bilgileri',
    footer_copy:     '© 2026 CEYSAN Alüminyum. Tüm hakları saklıdır.',
    // Contact
    contact_address: 'Esenevler Mah. Cengiz Topel Cad. No:150/152-B, Ümraniye / İstanbul',
    contact_phone1:  '0216 520 57 34',
    contact_phone2:  '0532 451 42 33',
    contact_email:   'info@ceysanaluminyum.com.tr',
    contact_hours:   'Pzt–Cmt: 08:00 – 18:00',
    // Quote form
    quote_step1:     'Ürün Seçimi',
    quote_step2:     'Bilgiler',
    quote_step3:     'Onay',
    quote_title:     'Teklif Formu',
    quote_name:      'Ad Soyad',
    quote_phone:     'Telefon',
    quote_email:     'E-posta',
    quote_product:   'Ürün Kategorisi',
    quote_district:  'İlçe',
    quote_note:      'Notunuz',
    quote_submit:    'Teklif İste',
    quote_next:      'Devam Et',
    quote_prev:      'Geri',
    quote_success:   'Talebiniz alındı! En kısa sürede iletişime geçeceğiz.',
    // WA tooltip
    wa_tooltip:      'WhatsApp\'tan Yaz',
    // Page titles
    page_products:   'Ürünlerimiz',
    page_corporate:  'Kurumsal',
    page_gallery:    'Galeri',
    page_quote:      'Teklif Al',
    page_contact:    'İletişim',
  },
  en: {
    nav_home:        'Home',
    nav_products:    'Products',
    nav_corporate:   'About',
    nav_gallery:     'Gallery',
    nav_quote:       'Get Quote',
    nav_contact:     'Contact',
    hero_label:      '20+ Years of Experience',
    hero_title:      'Aluminium & PVC Joinery Systems',
    hero_title_hl:   'Professional Solutions',
    hero_sub:        'Based in Ümraniye, our company provides glass balcony, PVC window, aluminium joinery and more throughout Istanbul.',
    hero_cta1:       'Get a Quote',
    hero_cta2:       'Our Products',
    hero_stat1_num:  '20',
    hero_stat1_lbl:  'Years of Experience',
    hero_stat2_num:  '5000',
    hero_stat2_lbl:  'Completed Projects',
    hero_stat3_num:  '15',
    hero_stat3_lbl:  'Product Categories',
    prod_label:      'Product Categories',
    prod_title:      'Explore All Systems',
    prod_sub:        'Comprehensive solutions for your home, workplace and outdoor spaces across 15 product categories.',
    prod_detail:     'Explore',
    prod_all:        'View All Products',
    stat_exp:        'Years of Experience',
    stat_proj:       'Completed Projects',
    stat_cat:        'Product Categories',
    stat_dist:       'Districts Served',
    stat_sat:        'Customer Satisfaction',
    feat_label:      'Why CEYSAN?',
    feat_title:      'Quality & Trust You Can Rely On',
    feat_sub:        'With over 20 years of experience, we aim for the highest quality and customer satisfaction in every project.',
    feat1_title:     'Expert Team',
    feat1_desc:      'Our technical team with 20 years of experience is with you every step of your project.',
    feat2_title:     'On-Site Survey & Installation',
    feat2_desc:      'Free survey and professional installation — complete turnkey solutions.',
    feat3_title:     'Guaranteed Products',
    feat3_desc:      'All our systems are covered by warranty with after-sales service support.',
    feat4_title:     'Serving All Istanbul',
    feat4_desc:      'Fast and reliable installation service to all districts of Istanbul.',
    cta_title:       'Get a Free Survey & Quote',
    cta_sub:         'Our expert team will visit you on-site to offer the most suitable solution.',
    cta_btn1:        'Quote Form',
    cta_btn2:        'Message on WhatsApp',
    gal_label:       'Our Projects',
    gal_title:       'From Our Completed Work',
    gal_sub:         'We deliver quality and aesthetics together in every project.',
    gal_all:         'View Full Gallery',
    search_ph:       'Search products… (e.g. glass balcony)',
    search_no:       'No results found',
    search_hint1:    'ESC to close',
    search_hint2:    'Enter for first result',
    footer_desc:     'Based in Ümraniye, our company has been serving Istanbul for over 20 years in aluminium, PVC joinery and glass systems.',
    footer_menu:     'Menu',
    footer_products: 'Products',
    footer_contact:  'Contact Details',
    footer_copy:     '© 2026 CEYSAN Aluminium. All rights reserved.',
    contact_address: 'Esenevler Mah. Cengiz Topel Cad. No:150/152-B, Ümraniye / Istanbul',
    contact_phone1:  '+90 216 520 57 34',
    contact_phone2:  '+90 532 451 42 33',
    contact_email:   'info@ceysanaluminyum.com.tr',
    contact_hours:   'Mon–Sat: 08:00 – 18:00',
    quote_step1:     'Product',
    quote_step2:     'Details',
    quote_step3:     'Confirm',
    quote_title:     'Request a Quote',
    quote_name:      'Full Name',
    quote_phone:     'Phone',
    quote_email:     'Email',
    quote_product:   'Product Category',
    quote_district:  'District',
    quote_note:      'Notes',
    quote_submit:    'Request Quote',
    quote_next:      'Continue',
    quote_prev:      'Back',
    quote_success:   'Request received! We will contact you shortly.',
    wa_tooltip:      'Message on WhatsApp',
    page_products:   'Our Products',
    page_corporate:  'About Us',
    page_gallery:    'Gallery',
    page_quote:      'Get Quote',
    page_contact:    'Contact',
  }
};

/* ── Istanbul Districts (for quote form) ───────────────────────── */
CEYSAN.districts = [
  'Adalar','Arnavutköy','Ataşehir','Avcılar','Bağcılar','Bahçelievler','Bakırköy',
  'Başakşehir','Bayrampaşa','Beşiktaş','Beykoz','Beylikdüzü','Beyoğlu','Büyükçekmece',
  'Çatalca','Çekmeköy','Esenler','Esenyurt','Eyüpsultan','Fatih','Gaziosmanpaşa',
  'Güngören','Kadıköy','Kağıthane','Kartal','Küçükçekmece','Maltepe','Pendik',
  'Sancaktepe','Sarıyer','Silivri','Sultanbeyli','Sultangazi','Şile','Şişli',
  'Tuzla','Ümraniye','Üsküdar','Zeytinburnu'
];

/* ── Gallery Images ────────────────────────────────────────────── */
CEYSAN.gallery = [
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730795591592836906.jpeg', tr_cap: 'Cam Balkon', en_cap: 'Glass Balcony', span: 'span-2', cat: 'cam' },
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307956391740415725.jpeg', tr_cap: 'Alüminyum Doğrama', en_cap: 'Aluminium Joinery', span: '', cat: 'aluminyum' },
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307954501627680637.jpeg', tr_cap: 'Panjur Sistemleri', en_cap: 'Roller Shutters', span: 'span-row', cat: 'panjur' },
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730795703876593671.jfif', tr_cap: 'Otomatik Pergole', en_cap: 'Automatic Pergola', span: '', cat: 'dis-mekan' },
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307960201811398340.jpg', tr_cap: 'Duşakabin', en_cap: 'Shower Cabin', span: '', cat: 'ic-mekan' },
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307963211263789979.jpeg', tr_cap: 'Zip Perde', en_cap: 'Zip Screen', span: '', cat: 'dis-mekan' },
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_1730795825129986665.jfif', tr_cap: 'Giyotin Cam Balkon', en_cap: 'Guillotine Glass Balcony', span: '', cat: 'cam' },
  { src: 'https://ceysanaluminyum.com/resimler/urungrubu/urun_urungrubu_17307957991748509017.jpeg', tr_cap: 'Alüminyum Küpeşte', en_cap: 'Aluminium Handrail', span: '', cat: 'aluminyum' },
];

/* ── Company Info ──────────────────────────────────────────────── */
CEYSAN.company = {
  name_tr:   'CEYSAN Alüminyum ve PVC Doğrama Sistemleri',
  name_en:   'CEYSAN Aluminium & PVC Joinery Systems',
  phone1:    '02165205734',
  phone2:    '05324514233',
  phone1_fmt:'0216 520 57 34',
  phone2_fmt:'0532 451 42 33',
  wa:        '905324514233',
  email:     'info@ceysanaluminyum.com.tr',
  address_tr:'Esenevler Mah. Cengiz Topel Cad. No:150/152-B, Ümraniye / İstanbul',
  address_en:'Esenevler Mah. Cengiz Topel Cad. No:150/152-B, Ümraniye / Istanbul',
  instagram: 'https://instagram.com/ceysan.aluminyum',
  facebook:  'https://www.facebook.com/profile.php?id=100084981031864',
  logo:      'https://ceysanaluminyum.com/images/logo.png',
  mapEmbed:  'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3011.!2d29.093727!3d41.01219!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sCengiz+Topel+Cd.+No:150+Ümraniye%2Fİstanbul!5e0!3m2!1str!2str!4v1',
  hours_tr:  'Pzt – Cmt: 08:00 – 18:00',
  hours_en:  'Mon – Sat: 08:00 – 18:00',
};
